#ifndef _STRATEGY_SWITCH_H_
#define _STRATEGY_SWITCH_H_

#define CHECKOUT 4 // 8进6 保证第xx
#define RISEINRANK 2 // 8进4 保证第xx
#define CHECKOUT_REDUCE_HAND_STRENGTH 0.15
#define RISEINRANK_REDUCE_HAND_STRENGTH 0.1
#define CHECKOUT_REDUCE_RR 0.3
#define RISEINRANK_REDUCE_RR 0.2
#define CHECKOUT_SMALLBLIND 50
#define RISEINRANKT_SMALLBLIND 100
#define JettonProcetHS 0.65
#define RR_FLOD 0
#define JettonRemain 0.5
#define BetProcet 0.5
#define AVERAGEPLAYERNUM 2
#define FIVE_PLAYER_REDUCE_HAND_STRENGTH 0.15
#define FOUR_PLAYER_REDUCE_HAND_STRENGTH 0.1
#define THREE_PLAYER_REDUCE_HAND_STRENGTH 0.05
#define PLAYER_REDUCE_HAND_STRENGTH 0.2
#define GOLD_PROTECT 10000


#endif